apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: production
images:
- name: hello-gitops
  newName: harbor.dorn.tkg-aws-e2-lab.winterfell.katirap.xyz/build-service/hello-gitops
  newTag: aa86dad2bcffa584f7aa399d83bdc095121638c9
