apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
namespace: production
# patchesJson6902:
# - target:
#     group: extensions
#     version: v1beta1
#     kind: Ingress
#     name: my-ingress
#   path: ./ingress-patch.yaml
images:
- name: hello-gitops
  newName: gcr.io/pkatira-se/build-service/hello-gitops
  newTag: 9a9d235bd2f846f4beae9eb4942ad89bc85278c4
